---
abstract: 'DBIx Class Result Validation'
author:
  - 'Nicolas Oudard'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Result-Validation
provides:
  DBIx::Class::Result::Validation:
    file: lib/DBIx/Class/Result/Validation.pm
    version: 0.13
  DBIx::Class::Result::Validation::VException:
    file: lib/DBIx/Class/Result/Validation/VException.pm
    version: 0.11
requires:
  Carp: 0
  Class::Accessor::Grouped: 0.09008
  DBIx::Class: 0.08127
  Moose: 0
  SQL::Translator: 0.11007
  Test::More: 0
  Try::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/kolok/DBIx-Class-Result-Validation
version: 0.13
